### ISSUE TITLE
大佬问一下：使用DingTalk-Notifier分支，配置了企业微信群的告警，一个Cloud Watch 状态变化会发送两条告警，怎么配置可以只发送第二条不发送第一条？

### ISSUE THREAD

**Issue by Chris-wa-He** [Chris-wa-He/DingTalk-notifier#21]
大佬问一下：使用DingTalk-Notifier分支，配置了企业微信群的告警，一个Cloud Watch 状态变化会发送两条告警，怎么配置可以只发送第二条不发送第一条？
<img width="860" alt="image" src="https://github.com/Chris-wa-He/AWS-Lambda-notifier/assets/16249566/2ec335d6-043f-4d3b-b259-fd19c9ba0d38">

_Originally posted by @imshi in https://github.com/Chris-wa-He/AWS-Lambda-notifier/discussions/1#discussioncomment-9590836_

**Comment by Chris-wa-He** [comment]
Hi @imshi 

谢谢您的询问！
截图中的情况，第一条信息是原信息，第二条信息是经过转换的信息。正常部署情况下，应该只会收到第二条信息。请问您有添加或修改过EventBridge的rule吗？

检查步骤：
1. 查看并提供部署的DingTalk-Notifier版本。
2. 请打开EventBridge服务，在规则下，查看是否有如下类似的多条规则。
<img width="1417" alt="image" src="https://github.com/Chris-wa-He/AWS-Lambda-notifier/assets/52903590/3e323f89-d671-462b-ac98-b6b73b5ac4db">

谢谢！

**Comment by imshi** [comment]
感谢回复，已查明第一条原信息的来源：CloudWath里创建了Alarm，在Alarm的Notification中向SNS又投递了一次消息。将alarm中的Notification删除掉，在Cloud Watch状态变化时就只会收到第二条转化后的信息（来自EventBridge的rule）了，再次感谢~
